### ISSUE TITLE
extension UIWindow and use swizzling

### ISSUE THREAD

**Issue by Eysner** [KaneCheshire/ShowTime#60]
Thanks for you work, but i see some problems in youre solutions.

https://github.com/KaneCheshire/ShowTime/blob/8fdd276e8cbf7281d6bb372e7caf990397d3c2e9/Sources/ShowTime/ShowTime.swift#L193

It's bad practice to make extension UIWindow and use swizzling to intercept methods. You can potentially create serious problems for your application even though ShowTime can be turned off. ShowTime.enabled = never will ignored with youre code.

Also `always` is not good for default value, beacuse turn on should be explicit action.
https://github.com/KaneCheshire/ShowTime/blob/8fdd276e8cbf7281d6bb372e7caf990397d3c2e9/Sources/ShowTime/ShowTime.swift#L37

**Comment by KaneCheshire** [comment]
Hey, thanks for taking the time to raise an issue.

ShowTime is mostly designed just to be used for demoing when screen sharing and recording videos, and is designed to be a _very_ quick way to be able to show taps on screen _without_ having to subclass a `UIWindow`; with ShowTime you can immediately get taps showing on screen simply by including the package dependency, without the need to import ShowTime into any file or fiddle about with any settings, meaning people can very quickly show taps on screen for demos at work etc. 

This is also why it’s enabled by default but I understand this could be changed to `debugOnly` by default.

If we don’t swizzle, then we won’t be able to show taps on windows that we don’t own, which includes windows that Apple presents for things like share sheets and keyboards. 

The decision to swizzle in ShowTime is a conscious one, so that won’t be changing.
